# Generated by Django 5.0.3 on 2024-04-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolgApp', '0002_article_category_article_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('취미', '취미'), ('음식', '음식'), ('프로그래밍', '프로그래밍')], default='취미', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
